#!/usr/bin/env python3
"""
KernRift fuzz-program generator.

Produces syntactically valid .kr programs that exercise arithmetic,
bitwise, control-flow, and mixed integer/pointer operations. Each
generated program prints one or more u64 results on stdout. Python
acts as the oracle — we compute the expected output here and write
it alongside the .kr file as <name>.expected.

Usage:
    generate.py --out <dir> --count <N> --seed <S>

The differential harness picks up <dir> automatically — every .kr
gets compiled with --legacy and with the default IR backend, both
outputs get compared against each other AND against <name>.expected.
A three-way agreement means the generated program is deterministic
across backends and matches the Python oracle. Any disagreement is
a miscompile signal, captured verbatim (program + expected) into
tests/fuzz/regressions/.

Deterministic for a given seed. CI pins the seed; local runs can
vary to surface new shapes.
"""

import argparse
import os
import random
import sys

U64_MASK = (1 << 64) - 1


def u64(x: int) -> int:
    return x & U64_MASK


def rand_leaf(rng: random.Random) -> tuple[str, int]:
    """A literal or a simple nested expression."""
    kind = rng.randrange(6)
    if kind == 0:
        v = rng.randrange(0, 256)
        return (str(v), v)
    if kind == 1:
        v = rng.randrange(256, 65536)
        return (str(v), v)
    if kind == 2:
        v = rng.randrange(0, 1 << 31)
        return (str(v), v)
    if kind == 3:
        # Large value that forces movabsq (in legacy) / sign-extended imm (IR)
        v = rng.randrange(1 << 31, 1 << 63)
        return (str(v), v)
    if kind == 4:
        # Near-max
        v = U64_MASK - rng.randrange(0, 1024)
        return (f"0x{v:016X}", v)
    # Power of two
    shift = rng.randrange(0, 63)
    v = 1 << shift
    return (str(v), v)


def rand_expr(rng: random.Random, depth: int) -> tuple[str, int]:
    if depth <= 0 or rng.random() < 0.3:
        return rand_leaf(rng)
    op = rng.choice(["+", "-", "*", "/", "%", "&", "|", "^", "<<", ">>"])
    l_src, l_val = rand_expr(rng, depth - 1)
    r_src, r_val = rand_expr(rng, depth - 1)
    if op in ("/", "%") and r_val == 0:
        r_val = 1
        r_src = "1"
    if op == "<<" or op == ">>":
        # shift amount MUST be < 64 to be well-defined
        r_val = r_val % 64
        r_src = str(r_val)
    try:
        if op == "+":
            v = u64(l_val + r_val)
        elif op == "-":
            v = u64(l_val - r_val)
        elif op == "*":
            v = u64(l_val * r_val)
        elif op == "/":
            v = l_val // r_val  # u64 truncating division
        elif op == "%":
            v = l_val % r_val
        elif op == "&":
            v = l_val & r_val
        elif op == "|":
            v = l_val | r_val
        elif op == "^":
            v = l_val ^ r_val
        elif op == "<<":
            v = u64(l_val << r_val)
        elif op == ">>":
            v = l_val >> r_val
    except ZeroDivisionError:
        v = 0
    return (f"({l_src} {op} {r_src})", v)


def gen_arith(rng: random.Random, idx: int) -> tuple[str, list[int]]:
    """Generates a program that prints the result of N random expressions."""
    n_exprs = rng.randrange(4, 12)
    exprs: list[tuple[str, int]] = [rand_expr(rng, rng.randrange(2, 5)) for _ in range(n_exprs)]
    body = "\n".join(f"    println({src})" for src, _ in exprs)
    program = (
        "// generated by tests/fuzz/generate.py — do not edit manually\n"
        f"// idx={idx}\n"
        "fn main() {\n"
        f"{body}\n"
        "    exit(0)\n"
        "}\n"
    )
    expected = [v for _, v in exprs]
    return program, expected


def gen_control_flow(rng: random.Random, idx: int) -> tuple[str, list[int]]:
    """Program that computes a loop sum + conditional branches."""
    # sum = 0; for i in 1..=N: if i % 2 == K: sum += f(i)
    n = rng.randrange(5, 40)
    k = rng.randrange(0, 2)
    mult = rng.randrange(1, 11)
    add = rng.randrange(0, 101)
    # Python oracle
    total = 0
    for i in range(1, n + 1):
        if i % 2 == k:
            total = u64(total + i * mult + add)
    total = u64(total)
    # Emit
    program = (
        "// generated by tests/fuzz/generate.py — do not edit manually\n"
        f"// idx={idx}\n"
        "fn main() {\n"
        "    uint64 sum = 0\n"
        "    uint64 i = 1\n"
        f"    while i <= {n} {{\n"
        f"        if (i % 2) == {k} {{\n"
        f"            sum = sum + i * {mult} + {add}\n"
        "        }\n"
        "        i = i + 1\n"
        "    }\n"
        "    println(sum)\n"
        "    exit(0)\n"
        "}\n"
    )
    return program, [total]


def gen_fn_chain(rng: random.Random, idx: int) -> tuple[str, list[int]]:
    """Program that defines several helper functions and chains their calls."""
    # Generate 2–4 helper fns, each of the form:
    #   fn fN(uint64 x) -> uint64 { return (x + a) * b + c }
    n_fns = rng.randrange(2, 5)
    fns: list[tuple[int, int, int]] = [(rng.randrange(0, 256), rng.randrange(1, 7), rng.randrange(0, 100)) for _ in range(n_fns)]
    start = rng.randrange(0, 100)
    cur = start
    for a, b, c in fns:
        cur = u64(u64(cur + a) * b + c)
    cur = u64(cur)
    # Emit
    decls = []
    for i, (a, b, c) in enumerate(fns):
        decls.append(f"fn f{i}(uint64 x) -> uint64 {{ return (x + {a}) * {b} + {c} }}")
    fn_decls = "\n".join(decls)
    call_chain = f"f{n_fns - 1}("
    for i in range(n_fns - 2, -1, -1):
        call_chain += f"f{i}("
    call_chain += f"{start}" + ")" * n_fns
    program = (
        "// generated by tests/fuzz/generate.py — do not edit manually\n"
        f"// idx={idx}\n"
        f"{fn_decls}\n"
        "fn main() {\n"
        f"    println({call_chain})\n"
        "    exit(0)\n"
        "}\n"
    )
    return program, [cur]


GENERATORS = [gen_arith, gen_control_flow, gen_fn_chain]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="output dir for .kr and .expected files")
    ap.add_argument("--count", type=int, default=50)
    ap.add_argument("--seed", type=int, default=0xDEADBEEF)
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    rng = random.Random(args.seed)
    for idx in range(args.count):
        gen = rng.choice(GENERATORS)
        prog, expected = gen(rng, idx)
        name = f"{gen.__name__.replace('gen_', '')}_{idx:03d}"
        with open(os.path.join(args.out, f"{name}.kr"), "w") as f:
            f.write(prog)
        with open(os.path.join(args.out, f"{name}.expected"), "w") as f:
            for v in expected:
                f.write(f"{v}\n")
    print(f"generated {args.count} programs into {args.out} (seed={args.seed})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
