#!/usr/bin/env python3
# Emit compact \p{L} and \p{N} codepoint RANGES as MLRift arrays.
# Uses the `regex` module to match Oniguruma's property semantics; falls back
# to unicodedata categories (L*, N*) which agree for BMP+SMP here.
import sys
try:
    import regex as _re
    isL = lambda cp: bool(_re.match(r"\p{L}", chr(cp)))
    isN = lambda cp: bool(_re.match(r"\p{N}", chr(cp)))
except ImportError:
    import unicodedata as ud
    isL = lambda cp: ud.category(chr(cp)).startswith("L")
    isN = lambda cp: ud.category(chr(cp)).startswith("N")
def ranges(pred, hi=0x110000):
    out, s = [], None
    for cp in range(hi):
        if pred(cp):
            if s is None: s = cp
        elif s is not None:
            out.append((s, cp - 1)); s = None
    if s is not None: out.append((s, hi - 1))
    return out
def emit(name, rs):
    lines = [f"// GENERATED by scripts/gen_bpe_unicode_tables.py — do not edit.",
             f"static u64 {name}_N = {len(rs)}"]
    # flat lo,hi pairs in a data blob built at init
    flat = ",".join(f"0x{lo:x},0x{hi:x}" for lo, hi in rs)
    lines.append(f"// {name} ranges (lo,hi pairs): {len(rs)}")
    return "\n".join(lines), flat
L = ranges(isL); N = ranges(isN)
with open(sys.argv[1] if len(sys.argv) > 1 else "std/bpe_unicode.mlr", "w") as f:
    f.write("// GENERATED — \\p{L}/\\p{N} range tables for the BPE pre-tokenizer.\n")
    f.write(f"static u64 uni_L_count = {len(L)}\n")
    f.write(f"static u64 uni_N_count = {len(N)}\n")
    f.write("static u64 uni_L_lo = 0\nstatic u64 uni_L_hi = 0\n")
    f.write("static u64 uni_N_lo = 0\nstatic u64 uni_N_hi = 0\n")
    f.write("static u64 uni_tables_init = 0\n\n")
    def blob(name, rs):
        los = ",".join(f"0x{lo:x}" for lo,_ in rs)
        his = ",".join(f"0x{hi:x}" for _,hi in rs)
        return los, his
    Llo,Lhi = blob("L",L); Nlo,Nhi = blob("N",N)
    # store as init function filling alloc'd arrays (MLRift has no array literals)
    f.write("fn uni_tables_ensure() {\n    if uni_tables_init == 1 { return }\n")
    f.write(f"    uni_L_lo = alloc({len(L)}*8); uni_L_hi = alloc({len(L)}*8)\n")
    f.write(f"    uni_N_lo = alloc({len(N)}*8); uni_N_hi = alloc({len(N)}*8)\n")
    for i,(lo,hi) in enumerate(L):
        f.write(f"    store64(uni_L_lo+{i}*8, 0x{lo:x}); store64(uni_L_hi+{i}*8, 0x{hi:x})\n")
    for i,(lo,hi) in enumerate(N):
        f.write(f"    store64(uni_N_lo+{i}*8, 0x{lo:x}); store64(uni_N_hi+{i}*8, 0x{hi:x})\n")
    f.write("    uni_tables_init = 1\n}\n\n")
    f.write("""fn uni_bsearch(u64 lo_arr, u64 hi_arr, u64 n, u64 cp) -> u64 {
    u64 lo = 0; u64 hi = n
    while lo < hi {
        u64 mid = (lo + hi) / 2
        u64 rlo = 0; u64 rhi = 0
        unsafe { *((lo_arr + mid*8) as u64) -> rlo }
        unsafe { *((hi_arr + mid*8) as u64) -> rhi }
        if cp < rlo { hi = mid } else { if cp > rhi { lo = mid + 1 } else { return 1 } }
    }
    return 0
}
fn uni_is_letter(u64 cp) -> u64 { uni_tables_ensure(); return uni_bsearch(uni_L_lo, uni_L_hi, uni_L_count, cp) }
fn uni_is_number(u64 cp) -> u64 { uni_tables_ensure(); return uni_bsearch(uni_N_lo, uni_N_hi, uni_N_count, cp) }
""")
print("wrote std/bpe_unicode.mlr")
